import {ApiResponse, ExtraOptions} from "../../../request"

export type CaasL1CategoryGroupId =
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "7"
  | "8"
  | "9"
  | "10"
  | "11"
  | "12"
  | "13"
  | "14"
  | "15"
  | "16"

export type CaasL1CategoryGroupName =
  | "bills"
  | "business"
  | "cash"
  | "entertainment"
  | "gifts"
  | "shopping"
  | "health"
  | "household"
  | "income"
  | "other"
  | "rent"
  | "taxes"
  | "transfers"
  | "transport"
  | "repayments"
  | "mixed"

export type CaasL1CategoryType =
  | "expense"
  | "income"
  | "transfer"
  | "deferred"
  | "mixed"
  | "uncategorize"

export type CaasL2CategoryId =
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "7"
  | "8"
  | "9"
  | "10"
  | "11"
  | "12"
  | "13"
  | "14"
  | "15"
  | "16"
  | "17"
  | "18"
  | "19"
  | "20"
  | "21"
  | "22"
  | "23"
  | "24"
  | "25"
  | "26"
  | "27"
  | "28"
  | "29"
  | "30"
  | "31"
  | "32"
  | "33"
  | "34"
  | "35"
  | "36"
  | "37"
  | "38"
  | "39"
  | "40"
  | "41"
  | "42"
  | "43"
  | "44"
  | "45"
  | "92"
  | "94"
  | "96"
  | "98"
  | "100"
  | "102"
  | "104"
  | "106"
  | "108"
  | "110"
  | "112"
  | "114"
  | "115"
  | "116"
  | "117"
  | "118"
  | "119"
  | "120"
  | "255"
  | "mixed"

export type CaasL2CategoryName =
  | "automotive"
  | "charitable"
  | "clothing"
  | "education"
  | "entertainment"
  | "gasoline"
  | "groceries"
  | "healthcare"
  | "home-maintenance"
  | "home-improvement"
  | "insurance"
  | "cable"
  | "online"
  | "loans"
  | "mortgages"
  | "other"
  | "personal"
  | "rent"
  | "eating-out"
  | "travel"
  | "service"
  | "atm"
  | "cheques"
  | "hobbies"
  | "other-bills"
  | "telephone"
  | "utilities"
  | "pets"
  | "electronics"
  | "general"
  | "office-supplies"
  | "child"
  | "taxes"
  | "gifts"
  | "advertising"
  | "business"
  | "postage"
  | "printing"
  | "dues"
  | "office-maintenance"
  | "wages"
  | "gambling"
  | "transfers"
  | "savings"
  | "credit"
  | "securities"
  | "other-income"
  | "paychecks"
  | "investment"
  | "retirement"
  | "interest"
  | "expense"
  | "benefits"
  | "rental-income"
  | "pension-contributions"
  | "pension-withdrawals"
  | "investments"
  | "services"
  | "dividends"
  | "mixed"
  | "consulting"
  | "deposits"
  | "sales"
  | "rewards"
  | "uncategorized"

export interface CaasCategory {
  l2CategoryId: CaasL2CategoryId
  l2CategoryName: CaasL2CategoryName
  l1CategoryGroupId: CaasL1CategoryGroupId
  l1CategoryGroupName: CaasL1CategoryGroupName
}

export interface CaasCategoryGroup {
  l1CategoryGroupId: CaasL1CategoryGroupId
  l1CategoryGroupName: CaasL1CategoryGroupName
  l1CategoryType: CaasL1CategoryType
}

export interface CaasCategoriesRequests {
  caasGetCategories: (options?: ExtraOptions) => Promise<ApiResponse<CaasCategory[]>>
  caasGetCategoryGroups: (options?: ExtraOptions) => Promise<ApiResponse<CaasCategoryGroup[]>>
}
